[tool.hatch.envs.test]
dependencies = [
  "wxpython"
]

[[tool.hatch.envs.test.matrix]]
python = ["38", "39"]

[tool.hatch.build.targets.sdist]
exclude = [
  "/.github",
  "/docs",
]

[tool.hatch.build.targets.wheel]
packages = ["src"]

